import tempfile
import os
from urllib.request import urlopen
from collections import namedtuple

from path_helpers import path

from .silence import Silence
from .safe_cv import cv


CodecInfo = namedtuple('CodecInfo', 'fourcc name owner description')


# Cached list of codecs from http://www.fourcc.org/codecs.php as of:
#    Tue Dec 20 13:58:03 EST 2011
ALL_CODECS = [
    CodecInfo(fourcc='3IV1', name='3ivx', owner='3IVX', description='MPEG4-based codec. Used by 3ivx Delta 1.0-3.5. FOURCC &quot;3IV0&quot; was also used for a while but never publicly released.'),
    CodecInfo(fourcc='3IV2', name='3ivx', owner='3IVX', description='MPEG4-based codec. To be used for &quot;3ivx Delta 4.0.&quot;'),
    CodecInfo(fourcc='8BPS', name='Planar RGB Codec', owner='Apple?', description='RLE codec storing RGB image in planar format under Quicktime.'),
    CodecInfo(fourcc='AASC', name='Autodesk Animator codec', owner='Autodesk', description="This codec is part of Autodesk's discontinued Animator Studio for Windows.&nbsp;"),
    CodecInfo(fourcc='ABYR', name='?', owner='Kensington?', description='Apparently a low resolution, low frame rate (6fps)  codec similar toAJPGwhich is used in implementing movie capture in some digital cameras.'),
    CodecInfo(fourcc='ADV1', name='WaveCodec', owner='Loronix', description='Apparently used in various CCTV products.'),
    CodecInfo(fourcc='ADVJ', name='Avid M-JPEG', owner='Avid Technology', description='Also known as AVRn'),
    CodecInfo(fourcc='AEMI', name='Array VideoONE MPEG1-I Capture', owner='Array Microsystems', description="Array's codec used for I frame only MPEG1 AVI files"),
    CodecInfo(fourcc='AFLI', name='Autodesk Animator codec', owner='Autodesk', description="AVI equivalent of Autodesk's native FLI file format (presumably)."),
    CodecInfo(fourcc='AFLC', name='Autodesk Animator codec', owner='Autodesk', description='AVI equivalent of the FLC native file format.'),
    CodecInfo(fourcc='AJPG', name='?', owner='?', description='22fps JPEG-based codec used for movie capture by some digital cameras.'),
    CodecInfo(fourcc='AMPG', name='Array VideoONE MPEG', owner='Array Microsystems', description='Codec for Array VideoONE hardware-based MPEG compression system.'),
    CodecInfo(fourcc='ANIM', name='RDX', owner='Intel', description='?'),
    CodecInfo(fourcc='AP41', name='AngelPotion Definitive', owner='AngelPotion', description="Another hacked version of Microsoft's MP43 codec. One source recommends against installing this codec &quot;due to its occasional tendency to modify client structures&quot;. Apparently this means that it can destroy or otherwise mess up the&nbsp; HKEY_CLASSES_ROOT\\avifile section of your registry leaving some tools incapable of playing video any more."),
    CodecInfo(fourcc='ASLC', name='Alparysoft Lossless Codec', owner='Alparysoft', description='Codec offering approximately 5x compression in mathematically lossless mode or 5-15x compression in &quot;visually lossless&quot; operation.'),
    CodecInfo(fourcc='ASV1', name='Asus Video', owner='Asus', description='Codec supplied with the Asus TNT Video Capture adapter. Supposedly a very simple, DCT-based codec. Complete technical details can be foundhere.'),
    CodecInfo(fourcc='ASV2', name='Asus Video (2)', owner='Asus', description='New codec from Asus. Supposedly a very simple DCT codec. Complete technical details can be foundhere.'),
    CodecInfo(fourcc='ASVX', name='Asus Video 2.0', owner='Asus', description='Unusual codec which stores audio in the .avi file but puts the video in a companion .asv file.Click herefor information on how to play back these files on Windows 2000 PCs.'),
    CodecInfo(fourcc='AUR2', name='Aura 2 Codec - YUV 422', owner='Auravision', description='?'),
    CodecInfo(fourcc='AURA', name='Aura 1 Codec - YUV 411', owner='Auravision', description='?'),
    CodecInfo(fourcc='avc1', name='H.264', owner='Apple', description="Apple's version of the MPEG4 part 10/H.264 standard apparently."),
    CodecInfo(fourcc='AVRn', name='Avid M-JPEG', owner='Avid Technology', description='Also known as ADVJ in Quicktime files.'),
    CodecInfo(fourcc='BA81', name='Raw 8bit RGB Bayer', owner='?', description='This format stores raw 8bit Bayer samples. The Bayer color filter array is describedhere. I wonder if this is a duplicate ofBYR1?'),
    CodecInfo(fourcc='BINK', name='Bink Video', owner='RAD Game Tools', description="Pretty popular codec in Windows games. I'm not sure if this is available as a standard Windows codec but the web site makes it sound interesting enough to list here even if it does require non-standard tools to use."),
    CodecInfo(fourcc='BLZ0', name='?', owner='Blizzard', description='MPEG-4 codec used in WarCraft 3 movies.'),
    CodecInfo(fourcc='BT20', name='Prosumer Video', owner='Conexant', description='Codec optimised for realtime compression of YUV images. Download the ZIP and add VIDC.BT20=btvvc32.drv and VIDC.Y41P=btvvc32.drv to the [drivers32] section of your SYSTEM.INI to enable the codec'),
    CodecInfo(fourcc='BTCV', name='Composite Video Codec', owner='Conexant', description='This, now obsolete, format supported a special data format used by the Brooktree Bt2115 chipset which could perform &quot;software encoded video output&quot; - a kind of software TV-out capability.'),
    CodecInfo(fourcc='BW10', name='Broadway MPEG Capture/Compression', owner='Data Translation', description='Codec for Broadway hardware-based MPEG compression system.'),
    CodecInfo(fourcc='BYR1', name='Raw 8bit RGB Bayer', owner='?', description='This format stores raw 8bit Bayer samples. The Bayer color filter array is describedhere.'),
    CodecInfo(fourcc='BYR2', name='Raw 16bit RGB Bayer', owner='?', description='This format stores packed 16bit Bayer samples with 12bit precision. The Bayer color filter array is describedhere.'),
    CodecInfo(fourcc='CC12', name='YUV12 Codec', owner='Intel', description='?'),
    CodecInfo(fourcc='CDVC', name='Canopus DV Codec', owner='Canopus', description='Allegedly used with digital video cameras. TheCanopus download pagehas a free software-only version of this codec which will install on machines which are not equipped with their capture hardware.&nbsp;Apparently if you edit the AVI and change the FOURCC to dvsd, it will play with these codecs too.'),
    CodecInfo(fourcc='CFCC', name='DPS Perception', owner='Digital Processing Systems', description='Native format used when capturing AVIs using a DPS Perception adapter.'),
    CodecInfo(fourcc='CGDI', name='Camcorder Video', owner='Microsoft', description='AVI format used byOffice 97 camcorder application.'),
    CodecInfo(fourcc='CHAM', name='Caviara Champagne', owner='Winnov', description='?'),
    CodecInfo(fourcc='CMYK', name='Uncompressed CMYK', owner='Colorgraph', description='Uncompressed 32bpp CMYK as used in printing processes.'),
    CodecInfo(fourcc='CJPG', name='WebCam JPEG', owner='Creative Labs', description='Used by Creative Video Blaster Webcam Go control. Seeherefor info on how to download and install this codec.'),
    CodecInfo(fourcc='CPLA', name='YUV 4:2:0', owner='Weitek', description='This sounds like an uncompressed format to me. Anyone know?'),
    CodecInfo(fourcc='CRAM', name='Microsoft Video 1', owner='Microsoft', description='Allegedly identical to MSVC.'),
    CodecInfo(fourcc='CSCD', name='CamStudio&nbsp;Codec', owner='RenderSoftSoftware', description='Open source (GPL license) codec optimised for screen capture applications. Source download is available.'),
    CodecInfo(fourcc='CTRX', name='Citrix Scalable Video Codec', owner='Citrix?', description='?'),
    CodecInfo(fourcc='CVID', name='Cinepak', owner='Providenza &amp; Boekelheide', description='Originally owned by Supermac then Radius, nowP &amp; B. Complete technical details can be foundhere.'),
    CodecInfo(fourcc='CWLT', name='Color WLT DIB', owner='Microsoft', description='Apparently WLT is &quot;with lookup table&quot;. Presumably, therefore, this is similar to a standard DIB using FOURCC 0?'),
    CodecInfo(fourcc='CXY1', name='Conexant YUV 4:1:1', owner='Conexant', description='Uncompressed, planar 4:1:1&nbsp;YUV format.'),
    CodecInfo(fourcc='CXY2', name='Conexant YUV 4:2:2', owner='Conexant', description='Uncompressed, planar 4:2:2&nbsp;YUV format.'),
    CodecInfo(fourcc='CYUV', name='Creative YUV', owner='Creative Labs', description='Proprietary YUV compression algorithm'),
    CodecInfo(fourcc='CYUY', name='?', owner='ATI Technologies', description='Proprietary YUV compression algorithm'),
    CodecInfo(fourcc='D261', name='H.261', owner='DEC', description='Presumably now owned by Intel.'),
    CodecInfo(fourcc='D263', name='H.263', owner='DEC', description='Presumably now owned by Intel.'),
    CodecInfo(fourcc='davc', name='MPEG-4/H.264', owner='Dicas', description='H.264/MPEG-4 AVC base profile codec. Dicas tell me that this codec will be available for free download from their site some time in June 2004. I am waiting to hear the exact URL for the download.'),
    CodecInfo(fourcc='DCL1', name='Data Connection Conferencing Codec', owner='Data Connection Ltd.', description="Format used in Data Connection Ltd's conferencing services."),
    CodecInfo(fourcc='DCL2', name='Data Connection Multimedia Conferencing Codec', owner='Data Connection Ltd.', description="Format used in Data Connection Ltd's conferencing services."),
    CodecInfo(fourcc='DCL3', name='Data Connection Enhanced Conferencing Codec', owner='Data Connection Ltd.', description="Format used in Data Connection Ltd's conferencing services."),
    CodecInfo(fourcc='DCL4', name='Data Connection Extended Conferencing Codec', owner='Data Connection Ltd.', description="Format used in Data Connection Ltd's conferencing services."),
    CodecInfo(fourcc='DCL5', name='Data Connection Media  Conferencing Codec', owner='Data Connection Ltd.', description="Format used in Data Connection Ltd's conferencing services."),
    CodecInfo(fourcc='DIV3', name='DivX MPEG-4', owner='DivX', description='Low motion codec (optimised for low motion source material?). Several sources tell me that this is an old and illegal codec that should not be used to encode new material.'),
    CodecInfo(fourcc='DIV4', name='DivX MPEG-4', owner='DivX', description='Fast motion codec.Several sources tell me that this is an old and illegal codec that should not be used to encode new material.'),
    CodecInfo(fourcc='DIV5', name='?', owner='?', description="Apparently almost as old as DIV3 and DIV4. Changing DIV5 AVI's FOURCC to DIV3 or DIV4 seems to allow them to play just fine."),
    CodecInfo(fourcc='DIVX', name='DivX', owner='OpenDivX', description="This FOURCC code is used for versions 4.0 and later of the DivX codec. DivX, &quot;the MP3 of video,&quot;&nbsp; is the popular and market-leading MPEG-4 video codec that is emerging as the standard for full screen, full motion, DVD-quality video over IP-based networks.Apparently version 5 also encodes using FOURCCDX50.The Microsoft codec pack availablehereapparently supports Divx 6.This FOURCC is supported byLEAD's MCMP Codec."),
    CodecInfo(fourcc='divx', name='DivX', owner='?', description="Apparently used interchangeably with &quot;DIVX&quot;. This FOURCC is supported byLEAD's MCMP Codec."),
    CodecInfo(fourcc='DM4V', name='MPEG-4', owner='Dicas', description='MPEG4 codec compatible with DivX4 and 5.'),
    CodecInfo(fourcc='dmb1', name='Rainbow Runner hardware compression', owner='Matrox', description="Hardware codec used by Matrox Rainbow Runner video capture product. Apparently a form of Motion JPEG).LEAD's MCMP codecsupports this format."),
    CodecInfo(fourcc='DMB2', name='?', owner='?', description='MJPEG codec used by Paradigm.'),
    CodecInfo(fourcc='DMK2', name='?', owner='?', description='Movies generated by a ViewSonic V36 PDA appear to be AVI files using this video codec. Oddly enough, they are named .mpg - go figure.'),
    CodecInfo(fourcc='DSVD', name='DV Codec', owner='?', description="The DSVD codec is a VFW-based compressor that firewire- and DV-based capture cards use. It is supported by Graphedit (fromdivx-digest.com), Adobe Premier and StudioDV. VirtualDub doesn't support the format.I suspect that this and DVSD are one and the same - perhaps one of my informants typed the FOURCC wrongly?"),
    CodecInfo(fourcc='DUCK', name='TrueMotion S', owner='Duck Corporation', description='Rather nice RGB codec which, strangely enough, appears to have two distinct FOURCCs.'),
    CodecInfo(fourcc='dv25', name='DVCPRO', owner='Matrox', description='SMPTE 314M 25Mb/s compressed video. A professional variant of DVC (dvsd). Unlike dvsd, it uses 4:1:1 sampling structure for both NTSC and PAL.'),
    CodecInfo(fourcc='dv50', name='DVCPRO50', owner='Matrox', description='SMPTE 314M 50Mb/s compressed video. Has twice the data rate (50Mbits/sec) of dv25 and uses 4:2:2 sampling structure.'),
    CodecInfo(fourcc='DVAN', name='?', owner='?', description='?'),
    CodecInfo(fourcc='DVCS', name='DV Video', owner='Microsoft?', description='A generic DV codec along the same lines asDVSD. Microsoft indicatesherethat this codec should be considered obsolete now that standard FOURCCs for the various DV flavours have been defined.'),
    CodecInfo(fourcc='DVE2', name='DVE-2 Videoconferencing Codec', owner='InSoft', description='?'),
    CodecInfo(fourcc='dvh1', name='SMPTE 370M', owner='Panasonic?', description='SMPTE 370M - data structure for DV based audio, data and compressed video at 100 Mb/s - 1080/60i, 1080/50i, and 720/60p. This is basically a  high definition variant of dv25 and dv50.'),
    CodecInfo(fourcc='dvhd', name='50Mbps Consumer DV', owner='Microsoft?', description='SD-DVCR 1125-60 or SD-DVCR 1250-50. See alsodvslanddvsd.'),
    CodecInfo(fourcc='dvsd', name='25Mbps Consumer DV', owner='Pinnacle Systems?', description='SD-DVCR 525-60 or SD-DVCR 625-50. See alsodvslanddvhd.Implemented in the miroVideo DV300 SW only codec which requires the presence of the 1394 (Firewire) interface card with which it shipped.'),
    CodecInfo(fourcc='DVSD', name='DV Video', owner='Microsoft?', description='Used by Adobe After Effects, Uleads Mediastudio 6 (and probably VideoStudio) as a generic DV FOURCC. Probably the same as &quot;dvsd&quot;. Sources indicate that these FOURCCs were used interchangeably in early versions.&nbsp;Microsoft indicatesherethat this codec should be considered obsolete now that standard FOURCCs for the various DV flavours have been defined.'),
    CodecInfo(fourcc='dvsl', name='12.5Mbps Consumer DV', owner='Microsoft?', description='SD-DVCR 525-60 or SD-DVCR 625-50. See alsodvsdanddvhd.'),
    CodecInfo(fourcc='DVX1', name='DVX1000SP Video Decoder', owner='Lucent', description='?'),
    CodecInfo(fourcc='DVX2', name='DVX2000S Video Decoder', owner='Lucent', description='?'),
    CodecInfo(fourcc='DVX3', name='DVX3000S Video Decoder', owner='Lucent', description='?'),
    CodecInfo(fourcc='DX50', name='DivX MPEG-4version 5', owner='DivX', description='Apparently this is used interchangeably with the DIVX FOURCC when using version 5 of the codec. An alternative download site can be foundhere.'),
    CodecInfo(fourcc='DXGM', name='?', owner='Electronic Arts?', description='The movies in the game &quot;Lord of the Rings: Return of the King&quot; are encoded in this format. Also used in movies from &quot;Robin Hood&quot; byCinemaWare.'),
    CodecInfo(fourcc='DXTn', name='DirectX Compressed Texture', owner='Microsoft', description="5 different versions (DXT1 - DXT5) of compressed texture formats exist. Full documentation is to be found in the DirectX SDK. More info can also be found onS3's Texture Compression web site."),
    CodecInfo(fourcc='DXTC', name='DirectX Texture Compression', owner='Microsoft', description='Another of the DXTn set, I suppose.'),
    CodecInfo(fourcc='ELK0', name='?', owner='Elsa', description='Codec used by some Elsa graphics cards. May be a YUV format with reduced colour resolution.'),
    CodecInfo(fourcc='EKQ0', name='Elsa Quick Codec', owner='Elsa', description='?'),
    CodecInfo(fourcc='EM2V', name='Etymonix MPEG-2 Video', owner='Etymonix', description='HIgh quality, MPEG-2 I picture codec with user selectable YUV 4:2:0, 4:2:2 or 4:4:4 compression. Suitable for use in video editing applications. Free trial version available.'),
    CodecInfo(fourcc='ES07', name='Eyestream 7 Codec', owner='Eyeball&nbsp;Chat', description=''),
    CodecInfo(fourcc='ESCP', name='Escape', owner='Eidos Technologies', description='Codec used by Eidos Technologies ESCAPE VideoStudio.'),
    CodecInfo(fourcc='ETV1', name='eTreppid Video Codec', owner='eTreppid Technologies', description='?'),
    CodecInfo(fourcc='ETV2', name='eTreppid Video Codec', owner='eTreppid Technologies', description='?'),
    CodecInfo(fourcc='ETVC', name='eTreppid Video Codec', owner='eTreppid Technologies', description='?'),
    CodecInfo(fourcc='FFV1', name='FFMPEG Codec', owner='Michael Niedermayer', description='A lossless video codec based on arithmetic coding developed in the open sourceffmpeg project.'),
    CodecInfo(fourcc='FLJP', name='Field Encoded Motion JPEG', owner='D-Vision', description='Field encoded motion JPEG with LSI bitstream format. Morgan Multimedia offers acodec supporting this format.'),
    CodecInfo(fourcc='FMP4', name='FFMpeg', owner='?', description='The default MPEG4 format used by tool mencoder.&nbsp;DirectShow filters supporting the codec are availablehere.'),
    CodecInfo(fourcc='FMVC', name='FM&nbsp;Screen Capture Codec', owner='Fox Magic Software?', description='A codec intended for use in screen capture applications.'),
    CodecInfo(fourcc='FPS1', name='Fraps Codec', owner='Fraps', description='Codec used by Fraps screen video capture application.'),
    CodecInfo(fourcc='FRWA', name='Forward Motion JPEG with alpha channel', owner='SoftLab-Nsk', description='A version of motion JPEG as used in the Forward project from SoftLab-Nsk. This format also includes an 8-bit alpha channel per image.'),
    CodecInfo(fourcc='FRWD', name='Forward Motion JPEG', owner='SoftLab-Nsk', description='A version of motion JPEG as used in the Forward project from SoftLab-Nsk. Similar to FRWD but without the alpha information.'),
    CodecInfo(fourcc='FVF1', name='Fractal Video Frame', owner='Iterated Systems', description='&nbsp;'),
    CodecInfo(fourcc='GEOX', name='GEOMPEG4', owner='GeoVision', description="MPEG shipped as part of GeoVision's CCTV surveillance systems."),
    CodecInfo(fourcc='GJPG', name='GT891x Codec', owner='Grand Tech', description='Shipped as part of the driver package with some dgital cameras from Fuji.'),
    CodecInfo(fourcc='GLZW', name='Motion LZW', owner='gabest@freemail.hu', description='GIF-like codec written bygabest@freemail.hu.'),
    CodecInfo(fourcc='GPEG', name='Motion JPEG', owner='gabest@freemail.hu', description='Motion JPEG codec written as a learning exercise bygabest@freemail.hu.'),
    CodecInfo(fourcc='GWLT', name='Greyscale WLT DIB', owner='Microsoft', description='8bpp greyscale image. WLT apparently means &quot;with lookup table&quot; so it is a palettized format.'),
    CodecInfo(fourcc='H260 throughH269', name='ITU H.26n', owner='Intel', description='Conferencing codecsH.263 format video is for POTS-based videoconferencing. Used, for example, in someOspreyproducts.Supposedly, the Vanguard SoftwareH.264codec,available in beta form here, is pretty good.'),
    CodecInfo(fourcc='HDYC', name='Raw YUV 4:2:2', owner='?', description='This is apparently identical toUYVYexcept that the samples use BT709 color space (as used in HD video) rather than BT470 (used for SD).'),
    CodecInfo(fourcc='HFYU', name='Huffman Lossless Codec', owner='?', description='Huffman codec for YUV and RGB formats. Available in source and DLL forms. Full technical information can be foundhere. I am told that further information can also be foundhere.'),
    CodecInfo(fourcc='HMCR', name='Rendition Motion Compensation Format', owner='Rendition', description='Proprietary motion compensation surface format used by Rendition V2x00 DirectDraw driver.'),
    CodecInfo(fourcc='HMRR', name='Rendition Motion Compensation Format', owner='Rendition', description='Newer, proprietary motion compensation surface format used by Rendition drivers.'),
    CodecInfo(fourcc='i263', name='ITU H.263', owner='Intel', description="PictureWorks NetCard Player - another H.263 implementation from Intel. There's a FAQ on this codechereand it can also be downloaded fromhere."),
    CodecInfo(fourcc='IAN', name='Indeo 4 Codec', owner='Intel', description='One of a collection of FOURCCs used in Indeo 4.'),
    CodecInfo(fourcc='ICLB', name='CellB Videoconferencing Codec', owner='InSoft', description='?'),
    CodecInfo(fourcc='IGOR', name='Power DVD', owner='?', description='?'),
    CodecInfo(fourcc='IJPG', name='Intergraph JPEG', owner='Intergraph', description="Intergraph's version of a JPEG codec (don't you hate it when I just state the obvious ?)"),
    CodecInfo(fourcc='ILVC', name='Layered Video', owner='Intel', description='?'),
    CodecInfo(fourcc='ILVR', name='ITU H.263+ Codec', owner='?', description='?'),
    CodecInfo(fourcc='IPDV', name='Giga AVI DV Codec', owner='I-O Data Device, Inc.', description="Codec used with I-O Data Device's IEEE1394 Digital Video Control &amp; Capture Board. This codec implements I-O DATA's original indexed AVI architecture."),
    CodecInfo(fourcc='IR21', name='Indeo 2.1', owner='Intel', description='Old Indeo codec'),
    CodecInfo(fourcc='IRAW', name='Intel Uncompressed UYUV', owner='Intel', description='No indication of the pixel format - sorry.'),
    CodecInfo(fourcc='ISME', name='?', owner='?', description='May be installed byRoxioDVD Creator 6?'),
    CodecInfo(fourcc='IV30 throughIV39', name='Indeo 3', owner='Ligos', description='The family of Indeo Video 3 codecs originally developed by Intel but now handled by Ligos.'),
    CodecInfo(fourcc='IV32', name='Indeo 3.2', owner='Ligos', description='Fairly widespread Indeo 3 codec'),
    CodecInfo(fourcc='IV40 throughIV49', name='Indeo Interactive', owner='Ligos', description='Indeo 4.1 improves image quality and introduces transparency masks. Ligos also offer a downloadherebut apparently it will cost you.'),
    CodecInfo(fourcc='IV50', name='Indeo Interactive', owner='Ligos', description='Version 5.0 of the Indeo codec series designed for internet video delivery. Ligos also offer a downloadherebut apparently it will cost you.'),
    CodecInfo(fourcc='JBYR', name='?', owner='Kensington?', description='?'),
    CodecInfo(fourcc='jpeg', name='JPEG Still Image', owner='Microsoft?', description="This is presumably exactly the same as &quot;JPEG&quot;.LEAD's MCMP codecsupports both these formats."),
    CodecInfo(fourcc='JPEG', name='JPEG Still Image', owner='Microsoft', description="This is presumably exactly the same as &quot;jpeg&quot;.LEAD's MCMP codecsupports both these formats."),
    CodecInfo(fourcc='JPGL', name='JPEG Light?', owner='?', description="Proprietary format used by many WebCams which are built around the DIVIO NW 801/802 chip such as the Logitec QuickCam Pro, VideoLogic HomeC@m and other cameras from Askey, Mustek, Microtek, and Tekom.LEAD's MCMP codecsupports this format."),
    CodecInfo(fourcc='KMVC', name="Karl Morton's Video Codec (presumably)", owner='?', description='Shipped as part of the game &quot;Worms&quot; by Team17 Software. Info is allegedly obtainable frominfo@beamaim.demon.co.uk.'),
    CodecInfo(fourcc='L261', name='LEAD H.261', owner='LEAD Technologies', description='?'),
    CodecInfo(fourcc='L263', name='LEAD H.263', owner='LEAD Technologies', description='LEAD tell me that &quot;The LEAD H.263 codec is a high quality lossy interframe DirectShow and Video for Windows (VfW) codec with a quality and compression ratio comparable to MPEG-4. It can be used for a range of applications including video-conferencing, Internet video or surveillance and monitoring. Existing video software, such as Windows&reg; Media Player&reg; and Ulead Media Studio&reg; can utilize this codec to play, create, convert and edit.&quot;'),
    CodecInfo(fourcc='LBYR', name='?', owner='?', description='Based on the naming, I would hazard a guess that this describes some Bayer image format and may have been registered by LEAD Technologies. Can anyone confirm or deny?'),
    CodecInfo(fourcc='LCMW', name='LEAD&nbsp;MCMW Video Codec', owner='LEAD Technologies', description='This is a wavelet-based codec. LEAD tell me &quot;The MCMW Codec is designed to create high-quality video using low bandwidth (dial-up) delivery. This is achieved by using a state of the art intraframe wavelet based compression technique that provides superior compression performance, while still ensuring optimal quality at any compression level.&quot;'),
    CodecInfo(fourcc='LCW2', name='LEAD MJPEG2000', owner='LEAD Technologies', description='Codec saving standard JPEG2000 streams. LEAD has more info about ithere.'),
    CodecInfo(fourcc='LEAD', name='LEAD Video Codec', owner='LEAD Technologies', description="LEAD tell me that this codec is now obsolete yet it seems that their &quot;MCMP Codec&quot; supports it so&nbsp;I guess it's not as obsolete as all that."),
    CodecInfo(fourcc='LGRY', name='Grayscale Image', owner='LEAD Technologies', description='Supports 12 and 16bpp grayscale images with additional low and high range information required for medical images. Format public but not finalised when this update was made.'),
    CodecInfo(fourcc='LJ11', name='LEAD JPEG 4:1:1', owner='LEAD Technologies', description="Presumably a JPEG codec which encodes YUV in 4:1:1 format. This is supported byLEAD's MCMP Codec."),
    CodecInfo(fourcc='LJ22', name='LEAD JPEG 4:2:2', owner='LEAD Technologies', description="Presumably a JPEG codec which encodes YUV in 4:2:2 format. This is supported byLEAD's MCMP Codec."),
    CodecInfo(fourcc='LJ2K', name='LEAD MJPEG 2000', owner='LEAD Technologies', description='LEAD&nbsp;tell me &quot;the LEAD MJPEG2000 Video codec saves standard JPEG2000 streams. This codec is perfect when high compression and interoperability are necessary.&quot;'),
    CodecInfo(fourcc='LJ44', name='LEAD JPEG 4:4:4', owner='LEAD Technologies', description="Presumably a JPEG codec which encodes YUV in 4:4:4 format. This is supported byLEAD's MCMP Codec."),
    CodecInfo(fourcc='Ljpg', name='LEAD MJPEG Codec', owner='LEAD Technologies', description='Supports color JPEG 4:1:1, 4:2:2, 4:4:4, grayscale JPEG 4:0:0) FOURCCs supported: MJPG, JPEG, dmb1 Lossless JPEG support including 24-bit color and 8,12 and 16-bit grayscale. Link offers download of a time-expiring version of the codec. This format is supported by theLEAD MCMP and MJPEG2000 codecs.'),
    CodecInfo(fourcc='LMP2', name='LEAD MPEG-2 Video Codec', owner='LEAD Technologies', description="LEAD's implementation of the MPEG-2 video compression standard. The codec linked here also supports several other standard MPEG2 FOURCCs. Supports High, Main and Simple profiles,  Low, Main, High1440 and&nbsp;High levels."),
    CodecInfo(fourcc='LMP4', name='LEAD MPEG-4 Video Codec', owner='LEAD Technologies', description='An H.264 codec suporting Main and Base Profles and levels up to 3.2. LEAD offer two versions of this codec,  a normal version and a professional version which offers more options and higher compression ratios.'),
    CodecInfo(fourcc='LSVC', name='Lightning Strike Video&nbsp;Codec', owner='ESPRE Solutions', description='Old version of the codec now identified asLSVX.'),
    CodecInfo(fourcc='LSVM', name='Lightning Strike Video&nbsp;Codec', owner='ESPRE Solutions', description='Another old version of the codec now identified asLSVX.'),
    CodecInfo(fourcc='LSVX', name='Lightning Strike Video&nbsp;Codec', owner='ESPRE Solutions', description='Multi-bitrate decoder used in the eViewStreamX product.'),
    CodecInfo(fourcc='LZO1', name='Lempel-Ziv-Oberhumer Codec', owner='Markus Oberhumer', description='A fast, lossless codec available in source code format.'),
    CodecInfo(fourcc='M263', name='H.263', owner='Microsoft', description="Redmond's codec implementing the H.263 compression standard."),
    CodecInfo(fourcc='M261', name='H.261', owner='Microsoft', description="Redmond's codec implementing the H.261 compression standard."),
    CodecInfo(fourcc='M4CCm4cc', name='MPEG-4', owner='Divio', description=''),
    CodecInfo(fourcc='M4S2', name='MPEG-4(automatic WMP download)', owner='Microsoft', description='Final fully-compliant ISO MPEG4 decoder, compliant to MPEG-4 version 2 simple profile. An alternative download site can be foundhere.'),
    CodecInfo(fourcc='MC12', name='Motion Compensation Format', owner='ATI Technologies', description='Proprietary format used by ATI in MPEG decoding.'),
    CodecInfo(fourcc='MCAM', name='Motion Compensation Format', owner='ATI Technologies', description='Proprietary format used by ATI in MPEG decoding.'),
    CodecInfo(fourcc='MJ2C', name='Motion JPEG 2000', owner='Morgan Multimedia', description='Motion JPEG 2000'),
    CodecInfo(fourcc='mJPG', name='Motion JPEG including Huffman Tables', owner='IBM', description='A version of Motion JPEG which includes Huffman tables with each AVI frame. Developed by IBM before the MJPEG standard was finalised.'),
    CodecInfo(fourcc='MJPG', name='Motion JPEG', owner='?', description="Motion JPEG video. Codecs implementing MJPEG are (or have been) available fromhttp://www.jpg.com/imagetech_video.htmhttp://www.pmatrix.comPegasus ImagingMorgan Multimedia(long trial period)The format is also used byMatroxin their Rainbow Runner add-on video capture / MPEG playback board for various of their display adapters and by Canon who's cameras generate AVIs using this codec."),
    CodecInfo(fourcc='MMES', name='MPEG-2 ES', owner='Matrox', description='Matrox MPEG-2 video elementary stream.MPEG-2 main profile or 4:2:2 profile closed GOP IBP or I-frame only decoder.'),
    CodecInfo(fourcc='MP2A', name='Eval download', owner='Media Excel', description='MPEG-2 Audio'),
    CodecInfo(fourcc='MP2T', name='Eval download', owner='Media Excel', description='MPEG-2 Transport Stream'),
    CodecInfo(fourcc='MP2V', name='Eval download', owner='Media Excel', description='MPEG-2 Video'),
    CodecInfo(fourcc='MP42', name='MPEG-4(automatic WMP download)', owner='Microsoft', description='Apparently one of several different and incompatible MPEG-4 codecs. Rumour has it that this codec is downloadable from the Microsoft site somewhere. This codec is distributed as part of Microsoft Windows Media Tools 4. Includes quality improvements over the earlier MPG4.Download as part of &quot;Windows Media Codecs 8.0 for IT Professionals.&quot;'),
    CodecInfo(fourcc='MP43', name='MPEG-4(automatic WMP download)', owner='Microsoft', description="Yet another MPEG-4 variation from Microsoft. This FOURCC is not, however, listed on Microsoft's codecs site.&nbsp;This codec is distributed as part of Microsoft Windows Media Tools 4. Includes further quality improvements over the earlier MPG4."),
    CodecInfo(fourcc='MP4A', name='Eval download', owner='Media Excel', description='MPEG-4 Audio'),
    CodecInfo(fourcc='MP4S', name='MPEG-4(automatic WMP download)', owner='Microsoft ?', description='The first ISO standard codec for use with the Sharp digital camera implementing a restricted feature set of MPEG4.'),
    CodecInfo(fourcc='MP4T', name='Eval download', owner='Media Excel', description='MPEG-4 Transport Stream'),
    CodecInfo(fourcc='mp4v', name='MPEG-4', owner='?', description="Presumably a duplicate of MP4V. LEAD's MCMP codec supports this format and you can download an evaluation versionhere."),
    CodecInfo(fourcc='MP4V', name='Eval download', owner='Media Excel', description="MPEG-4 Video.LEAD's&nbsp;MCMP codecalso supports this format."),
    CodecInfo(fourcc='MPEG', name='MPEG', owner='?', description='MPEG video - presumably MPEG I ?'),
    CodecInfo(fourcc='MPG4', name='MPEG-4(automatic WMP download)', owner='Microsoft', description='MPEG-4 Video High Speed Compressor.Downloadable here, I am told. This codec was shipped with some versions of the Microsoft Netshow encoder (probably 3.0). This codec was based on early drafts of the MPEG-4 spec.'),
    CodecInfo(fourcc='MPGI', name='MPEG', owner='Sigma Designs', description='Editable MPEG codec'),
    CodecInfo(fourcc='MR16', name='?', owner='?', description='?'),
    CodecInfo(fourcc='MRCA', name='Mrcodec', owner='FAST Multimedia', description='And I thought it stood for &quot;Multi Role Combat Aircraft&quot;.'),
    CodecInfo(fourcc='MRLE', name='Microsoft RLE', owner='Microsoft', description="Run length encoded RGB format from Microsoft. Basically the same as the BI_RLE formats butMichael Knappclarifies:&quot;MRLE is just *nearly* the same compression as the existing 4 and 8bit RLE formats but the 'copy bytes-chunk' always has an even byte-length. That means that an empty byte is added if the 'copy chunk' contains an odd number of bytes&quot;"),
    CodecInfo(fourcc='MSVC', name='Microsoft Video 1', owner='Microsoft', description='Original codec shipped with Video For Windows. Deals with 8bpp and 16bpp images. Quality leaves a lot to be desired (IMHO). Full technical details are availablehere.'),
    CodecInfo(fourcc='MSZH', name='AVImszh', owner='Kenji Oshima', description='Kenji Oshima also developed a multi-threaded M3JPEG codec based on one by Morgan Multimedia. You candownload this here.Algorithm information can be foundhere. This is supposedly the same thing asZLIB.'),
    CodecInfo(fourcc='MTX1throughMTX9', name='?', owner='Matrox', description='Apparently these are MJPG variations registered by Matrox consumer products group.'),
    CodecInfo(fourcc='MVI1', name='Motion Pixels MVI1 Codec', owner='?', description='Part of the Motion Pixels player. Install the player and the codec will become available to other multimedia applications. Read moreat this site (look for Treasure Quest).'),
    CodecInfo(fourcc='MVI2', name='Motion Pixels MVI2 Codec', owner='?', description='As for MVI1, this is part of the Motion Pixels player. Read moreat this site.'),
    CodecInfo(fourcc='MWV1', name='Aware Motion Wavelets', owner='Aware Inc.', description='Wavelet compression-based codec optimised for Intel MMX platforms. Allegedly downloadable fromhere. Codec filename is icmw_32.dll.'),
    CodecInfo(fourcc='nAVI', name='Download here', owner='?', description='?'),
    CodecInfo(fourcc='NDSC', name='Nero&nbsp;Digital&nbsp;Cinema', owner='Nero Digital', description='Nero registered this with me recently but provided no information other than the name - sorry.'),
    CodecInfo(fourcc='ndsm', name='Nero MPEG4?', owner='Nero Digital', description='A contributor suggests that this codec is owned by Nero&nbsp;Digital and refer sto their flavour of MPEG4 but I have not been able to confirm this.'),
    CodecInfo(fourcc='ndsp', name='Nero Digital Portable', owner='Nero Digital', description='Nero have registered NDSP so my assumption is that they get the lower case version for free.'),
    CodecInfo(fourcc='NDSP', name='Nero Digital Portable', owner='Nero Digital', description='Apparently an MPEG4 implementation of some description.'),
    CodecInfo(fourcc='ndss', name='Nero Digital Standard', owner='Nero Digital', description='A contributor suggests that this codec is owned by Nero&nbsp;Digital and refers to their flavour of MPEG4 but I have not been able to confirm this.'),
    CodecInfo(fourcc='NDSS', name='Nero Digital Standard', owner='Nero Digital', description='Presumably the same as ndss.'),
    CodecInfo(fourcc='NDXC', name='Nero Digital AVC Cinema', owner='Nero Digital', description='Presumably a variation of MPEG4 part 10/AVC.'),
    CodecInfo(fourcc='NDXH', name='Nero Digital AVC HDTV', owner='Nero Digital', description='Presumably a variation of MPEG4 part 10/AVC.'),
    CodecInfo(fourcc='NDXP', name='Nero Digital AVC Portable', owner='Nero Digital', description='Presumably a variation of MPEG4 part 10/AVC.'),
    CodecInfo(fourcc='NDXS', name='Nero Digital AVC Standard', owner='Nero Digital', description='Presumably a variation of MPEG4 part 10/AVC.'),
    CodecInfo(fourcc='NTN1', name='Video Compression 1', owner='Nogatech/Zoran', description='?'),
    CodecInfo(fourcc='NTN2', name='Video Compression 2', owner='Nogatech/Zoran', description='An evolution of NTN1.'),
    CodecInfo(fourcc='NVDS', name='NVidia Texture Format', owner='NVidia', description='?'),
    CodecInfo(fourcc='NVHS', name='NVidia Texture Format', owner='NVidia', description='Apparently a texture format introduced for GEForce 3.'),
    CodecInfo(fourcc='NHVU', name='NVidia Texture Format', owner='NVidia', description='Apparently a texture format introduced for GEForce 3.'),
    CodecInfo(fourcc='NVS0-NVS5', name='?', owner='NVidia?', description='Supported by GEForce 2 GTS Pro / 64Mb DDR. Possibly a texture format.'),
    CodecInfo(fourcc='NVT0-NVT5', name='?', owner='NVidia?', description='Supported by GEForce 2 GTS Pro / 64Mb DDR. Possibly a texture format.'),
    CodecInfo(fourcc='PDVC', name='DVC codec', owner='I-O Data Device, Inc.', description='DV codec for I-O DATA Digital Video Capture products.'),
    CodecInfo(fourcc='PGVV', name='Radius Video Vision', owner='Radius', description='?'),
    CodecInfo(fourcc='PHMO', name='Photomotion', owner='IBM', description='?'),
    CodecInfo(fourcc='PIM1', name='Download here', owner='Pinnacle Systems', description='MPEG-1 based codec'),
    CodecInfo(fourcc='PIM2', name='?', owner='Pinnacle Systems', description='Pinnacle DC1000 firewire video editing card supports this format.'),
    CodecInfo(fourcc='pimj', name='Pegasus Lossless JPEG', owner='Pegasus Imaging', description='High speed compression and decompression of 24-bit RGB and 8-bit grayscale using Predictor 1 Lossless JPEG. Well suited for medical video. You may find additional informationhere.'),
    CodecInfo(fourcc='PIXL', name='Video XL', owner='Pinnacle Systems', description='This is apparently an alias forVIXL. You can find more information about ithere.'),
    CodecInfo(fourcc='PJPG', name='PA MJPEG', owner='Pierre Albou', description='Non-standard codec based on MJPEG.'),
    CodecInfo(fourcc='PVEZ', name='PowerEZ', owner='Horizons Technology', description="TrueMotion based codec (?) It appears that Horizons Technology has now been acquired by Raytheon and is no longer in the codec business (can someone confirm this - their URL is now redirected). Allegedly, you can download this codec from support.private.com but I'm not going to add a link since this is an adult video company and I don't want to get this site associated with porn."),
    CodecInfo(fourcc='PVMM', name='PacketVideo Corporation MPEG-4', owner='PacketVideo Corporation', description='Software MPEG4 codec that supports multiple bitrate encoding/decoding. It is also error resilient allowing transmission over wired/wireless networks.'),
    CodecInfo(fourcc='PVW2', name='Pegasus Wavelet 2000 Compression', owner='Pegasus Imaging', description="High speed compression and decompression of 24-bit RGB and 8-bit grayscale using  Pegasus' proprietary Wavelet2000 wavelet technology. Well suited for low motion, low bandwidth applications. More information is availablehere."),
    CodecInfo(fourcc='qpeq', name='QPEG 1.1', owner='Q-Team', description='?'),
    CodecInfo(fourcc='QPEG', name='QPEG', owner='Q-Team', description="Q-Team Dr.Knabe's 8-bit output codec with automatic palette switching for seamless edits."),
    CodecInfo(fourcc='raw', name='Raw RGB', owner='?', description='Apparently this contains &quot;raw, uncompressed RGB bitmaps&quot;.'),
    CodecInfo(fourcc='RGBT', name='32 bit support', owner='Computer Concepts', description="That's odd. I registered RGBT at the same time as a bunch of other FOURCCs and it was granted. The format I registered is for 16- and 32-bit uncompressed RBG images with a transparency plane. Microsoft's codec site, however, lists Computer Concepts rather than Brooktree (Conexant) as the owner. Hmm..."),
    CodecInfo(fourcc='rle', name='Apple Animation', owner='Apple', description='Yes this really is lower case. This format is used to compress Quicktime files. Available in 1, 2, 4, 8, 16, 24 and 32bit flavors.'),
    CodecInfo(fourcc='RLE', name='Run Length Encoder', owner='Microsoft?', description='I expect this is an equivalent to one of the the BI_RLEx FOURCCs (see theRGB page). The Win2K clock.avi sample uses this format. Final character in the FOURCC is a space.'),
    CodecInfo(fourcc='RLE4', name='4bpp Run Length Encoder', owner='Microsoft', description='Equivalent to BI_RLE4. SeeRGBpage for more details.'),
    CodecInfo(fourcc='RLE8', name='8bpp Run Length Encoder', owner='Microsoft', description='Equivalent to BI_RLE8. SeeRGBpage for more details.'),
    CodecInfo(fourcc='RMP4', name='MPEG-4 AS Profile Codec', owner='Sigma Designs', description='Press releaseheredescribes this codec.'),
    CodecInfo(fourcc='RPZA', name='Apple Video', owner='Apple', description='RGB555 block-based codec used in Quicktime files.'),
    CodecInfo(fourcc='RT21', name='Real Time Video 2.1', owner='Intel', description="What Indeo was called before the marketing guys got their hands on it. RTV or Real Time Video was the format produced by Intel's ActionMedia II adapter back in the late 80s. When the 80486 came along, this migrated to the software-decodable Indeo formats used today."),
    CodecInfo(fourcc='rv20', name='RealVideo G2', owner='Real', description='RealVideo G2 (6.0 and greater versions of the player and encoder)'),
    CodecInfo(fourcc='rv30', name='RealVideo 8', owner='Real', description=''),
    CodecInfo(fourcc='RV40', name='RealVideo 10?', owner='Real', description='Apparently you need to install&nbsp;RealPlayer 10 to enable playback of any AVI encoded with RV40.'),
    CodecInfo(fourcc='RVX', name='RDX', owner='Intel', description='?'),
    CodecInfo(fourcc='s422', name='VideoCap C210YUV Codec', owner='Tekram International', description="YUV422 codec shipped as part of the driver package for Tekram's C210 product."),
    CodecInfo(fourcc='SAN3', name='DivX 3', owner='?', description='A direct copy of DivX 3.11a, apparently. If you use a FOURCC changer tool on these AVIs they will play with the standard DivX codecs.'),
    CodecInfo(fourcc='SDCC', name='Digital Camera Codec', owner='Sun Communications', description='?'),
    CodecInfo(fourcc='SEDG', name='Samsung MPEG-4', owner='Samsung', description='MPEG-4 hardware and software codec used in Samsung digital video products.'),
    CodecInfo(fourcc='SFMC', name='Surface Fitting Method', owner='CrystalNet', description='CrystalGram video email codec.'),
    CodecInfo(fourcc='SMC', name='Apple Graphics', owner='Apple', description='8-bit, block-based codec used in Quicktime files.'),
    CodecInfo(fourcc='SMP4', name='?', owner='?', description='Codec used by Samsung VP-ms15 Digicam. This appears to be a DIVX clone since apparently SMP4 files play fine if you change the FOURCC to DIVX.'),
    CodecInfo(fourcc='SMSC', name='Proprietary codec', owner='Radius', description='?'),
    CodecInfo(fourcc='SMSD', name='Proprietary codec', owner='Radius', description='?'),
    CodecInfo(fourcc='smsv', name='Wavelet Video', owner='WorldConnect(corporate site)', description='Windows 95 codec installed automatically (and without warning) whenever you receive and play back a file sent fromVisualMail. Very low bandwidth format.'),
    CodecInfo(fourcc='SP40', name='?', owner='SunPlus', description='Appears to be an uncompressed YUV format of some kind but I&nbsp;have no information on this other than that.'),
    CodecInfo(fourcc='SP44', name='?', owner='SunPlus', description='Presumably a precursor to SP54?'),
    CodecInfo(fourcc='SP54', name='?', owner='SunPlus', description="Apparently a form of MJPEG but with some header or other missing. Software shipped with a number of low end digital cameras and webcams such asAiptek's Pocketcam digital still camera, Logitech's ClickSmart and Mustek's gSmart mini 2 use this format. These use SunPlus chipsets so presumably this explains the &quot;SP&quot;.You can download a tool that will convert this to MJPEGhere."),
    CodecInfo(fourcc='SPIG', name='Spigot', owner='Radius', description='?'),
    CodecInfo(fourcc='SQZ2', name='VXTreme Video Codec V2', owner='Microsoft', description='?'),
    CodecInfo(fourcc='SV10', name='Video R1', owner='Sorenson Media', description='Allegedly popular as a Quicktime codec. Used for trailer videos on Star Wars Episode 1 and other games.'),
    CodecInfo(fourcc='STVA', name='ST CMOS Imager Data (Bayer)', owner='ST Microelectronics', description='Data from ST CMOS Imagers that is passed to a codec external to the driver for processing to a displayable format. More info may be available at theST Vision and Imaging Unitweb site.'),
    CodecInfo(fourcc='STVB', name='ST CMOS Imager Data (Nudged Bayer)', owner='ST Microelectronics', description='Data from ST CMOS Imagers that is passed to a codec external to the driver&nbsp;for processing to a displayable format. More info may be available at theST Vision and Imaging Unitweb site.'),
    CodecInfo(fourcc='STVC', name='ST CMOS Imager Data (Bunched)', owner='ST Microelectronics', description='Data from ST CMOS Imagers that is passed to a codec external to the driver\t\t\t\t\t\t\t\t\nfor processing to a displayable format. More info may be available at theST Vision and Imaging Unitweb site.'),
    CodecInfo(fourcc='STVX', name='ST CMOS Imager Data (Extended CODEC Data Format)', owner='ST Microelectronics', description='Data from ST CMOS Imagers that is passed to a codec external to the driver\n\nfor processing to a displayable format. More info may be available at theST Vision and Imaging Unitweb site.'),
    CodecInfo(fourcc='STVY', name='ST CMOS Imager Data (Extended CODEC Data Format with Correction Data)', owner='ST Microelectronics', description='Data from ST CMOS Imagers that is passed to a codec external to the driver for processing to a displayable format. More info may be available at theST Vision and Imaging Unitweb site.'),
    CodecInfo(fourcc='SVQ1', name='Sorenson Video 1', owner='Sorenson Media', description='Hierarchicial adaptive multistage vector quantizer with mean removal and interframe motion compensation. Used in Quicktime. Complete technical details can be foundhere.'),
    CodecInfo(fourcc='SVQ3', name='Sorenson Video 3', owner='Sorenson Media', description='Video codec used in Quicktime files. A variant of H.264'),
    CodecInfo(fourcc='TLMS', name='Motion Intraframe Codec', owner='TeraLogic', description='?'),
    CodecInfo(fourcc='TLST', name='Motion Intraframe Codec', owner='TeraLogic', description='?'),
    CodecInfo(fourcc='TM20', name='TrueMotion 2.0', owner='Duck Corporation', description="Version 2.0 of Duck Corp's Truemotion codec. I'm told this codec is available as part of a pack that can be downloadedhere."),
    CodecInfo(fourcc='TM2X', name='TrueMotion 2X', owner='Duck Corporation', description="Duck Corp's follow-on codec after TM20."),
    CodecInfo(fourcc='TMIC', name='Motion Intraframe Codec', owner='TeraLogic', description='?'),
    CodecInfo(fourcc='TMOT', name='TrueMotion S', owner='Horizons Technology', description='Another FOURCC for TrueMotion S. This relates to the version of the codec licensed by Horizons Technology and is not compatible with DUCK.'),
    CodecInfo(fourcc='TR20', name='TrueMotion RT 2.0', owner='Duck Corporation', description='Realtime version of TrueMotion.'),
    CodecInfo(fourcc='TSCC', name='TechSmith Screen Capture Codec', owner='Techsmith Corp.', description='Codec used by theCamtasiaScreen &quot;camcorder&quot; application.'),
    CodecInfo(fourcc='TV10', name='Tecomac Low-Bit Rate Codec', owner='Tecomac, Inc.', description='?'),
    CodecInfo(fourcc='TVJP', name='?', owner='Pinnacle/Truevision', description='Used by the Targa 2000 board.'),
    CodecInfo(fourcc='TVMJ', name='?', owner='Pinnacle/Truevision', description='Used by the Targa 2000 board. Morgan Multimedia offers acodec supporting this format.'),
    CodecInfo(fourcc='TY2C', name='Trident Decompression Driver', owner='Trident Microsystems', description='?'),
    CodecInfo(fourcc='TY2N', name='?', owner='Trident Microsystems', description='?'),
    CodecInfo(fourcc='TY0N', name='?', owner='Trident Microsystems', description='?'),
    CodecInfo(fourcc='UCOD', name='ClearVideo', owner='eMajix.com', description='Fractal compression-based video codec available as a Video for Windows codec and in the ClearFusion Netscape plugin package.'),
    CodecInfo(fourcc='ULTI', name='Ultimotion', owner='IBM Corp.', description='Shipped with OS/2 but also available for Video for Windows. Link is to a very old version of the codec for Windows.'),
    CodecInfo(fourcc='v210', name='10-bit 4:2:2 Component YCbCr', owner='AJA&nbsp;Video Systems', description='Uncompressed format supported byAJA&nbsp;Video Systems Xenaadapter.'),
    CodecInfo(fourcc='V261', name='Lucent VX2000S', owner='Lucent', description='?'),
    CodecInfo(fourcc='V655', name='YUV 4:2:2', owner='Vitec Multimedia', description='Component ordering and packing unknown. Can you help?'),
    CodecInfo(fourcc='VCR1', name='ATI Video Codec 1', owner='ATI Technologies', description='Codec used by some ATI TV-PC products.'),
    CodecInfo(fourcc='VCR2', name='ATI Video Codec 2', owner='ATI Technologies', description='Codec used by some ATI TV-PC products.'),
    CodecInfo(fourcc='VCR3-9', name='ATI Video Codecs', owner='ATI Technologies', description="Registered for ATI Video Codecs version 3-9. I'm not sure these actually exist but the registrations are valid."),
    CodecInfo(fourcc='VDCT', name='VideoMaker Pro DIB', owner='Vitec Multimedia', description='16bpp format - no information on colour space, packing or component ordering.'),
    CodecInfo(fourcc='VDOM', name='VDOWave', owner='VDONet', description='Another streaming video format from VDONet.'),
    CodecInfo(fourcc='VDOW', name='VDOLive', owner='VDONet', description="H.263 internet streaming video format. Allegedly to be used (being used ?) by Microsoft in it's NetShow offering."),
    CodecInfo(fourcc='VDTZ', name='VideoTizer YUV Codec', owner='Darim Vision Co.', description="Codec used to store YUV AVIs captured with Darim Vision's VideoTizer product."),
    CodecInfo(fourcc='VGPX', name='VideoGramPix', owner='Alaris', description="Alaris VGPixel 32-bit AVI compression driver. It seems that this codec is installed along with the software for the &quot;Alaris Wee Cam.&quot;&nbsp; The codec doesn't appear to be available separately but, allegedly, works fine if you install theWee Cam softwareeven without the camera.&nbsp;You may also find some information athttp://www.alaris.com/vg_tech/vg_tchtx.htmandhttp://www.videogram.com."),
    CodecInfo(fourcc='VIFP', name='VFAPI Codec', owner='?', description='Take a look athttp://www.doom9.orgwhere you may find more information.'),
    CodecInfo(fourcc='VIDS', name='?', owner='Vitec Multimedia', description="YUV 4:2:2 CCIR 601 for V422 (no, I don't understand this either)"),
    CodecInfo(fourcc='VIVO', name='Vivo H.263', owner='Vivo Software', description="Vivo's version of the videoconferencing &quot;standard&quot; H.263 compression format (version 2.0.0)."),
    CodecInfo(fourcc='VIXL', name='Video XL', owner='Miro(now part of Pinnacle Systems)', description='Used my MiroVideo products such as the DC10, DC20, DC30, etc. A motion JPEG format that is accelerated in hardware with the Zoran chipset. You can find more information about ithere.'),
    CodecInfo(fourcc='VLV1', name='?', owner='VideoLogic', description="Codec probably used in VideoLogic's Captivator product line"),
    CodecInfo(fourcc='VP30', name='VP3', owner='On2', description="On2 tell me &quot;On2's VP3 codec will encode video into a VP3 file in multiple bit rates (roughly 220 Kbps, 330 Kbps, and 440 Kbps) and at optimum frame rates (usually 29.97 fps). This multiple bit rate file allows the TrueCast server to scale dynamically and smoothly as bandwidth congestion increases and decreases, providing the viewer with a consistent and reliable experience, without choppiness or interruption.&quot;"),
    CodecInfo(fourcc='VP31', name='VP31', owner='On2', description='The successor to VP30. This algorithm was open sourced by On2 in 2001-2002 and is the basis for theTheora Video Codec. Technical details are availablehere.'),
    CodecInfo(fourcc='VP40', name='VP40', owner='On2', description="Another in On2/Duck's line of video codecs."),
    CodecInfo(fourcc='VP50', name='VP50', owner='On2', description='..and another'),
    CodecInfo(fourcc='VP60', name='VP60', owner='On2', description='..and another'),
    CodecInfo(fourcc='VP61', name='VP61', owner='On2', description='..I can feel a pattern developing.'),
    CodecInfo(fourcc='VP62', name='VP62', owner='On2', description='..I wonder which one will be next?'),
    CodecInfo(fourcc='VQC1', name='VideoQuest Codec 1', owner='ViewQuest', description='Digital video camera codec.  ViewQuest offer lots of driver downloads on their site so you may find this in one of those packages.'),
    CodecInfo(fourcc='VQC2', name='VideoQuest Codec 2', owner='ViewQuest', description='Codec apparently used in Kodak DVC325 digital camera. Check the ViewQuest site download page - you may find the codec there somewhere.'),
    CodecInfo(fourcc='VQJC', name='?', owner='?', description='?'),
    CodecInfo(fourcc='vssv', name='VSS Video', owner='Vanguard Software Solutions', description='Real-time or near-real-time encoding with high compression ratios and good image quality.'),
    CodecInfo(fourcc='VUUU', name='?', owner='?', description='?'),
    CodecInfo(fourcc='VX1K', name='VX1000S Video Codec', owner='Lucent', description='?'),
    CodecInfo(fourcc='VX2K', name='VX2000S Video Codec', owner='Lucent', description='?'),
    CodecInfo(fourcc='VXSP', name='VX1000SP Video Codec', owner='Lucent', description='?'),
    CodecInfo(fourcc='VYU9', name='ATI YUV', owner='ATI Technologies', description='Planar YUV format supported by some ATI capture systems?'),
    CodecInfo(fourcc='VYUY', name='ATI YUV', owner='ATI Technologies', description='Packed YUV format supported by some ATI capture systems?'),
    CodecInfo(fourcc='WBVC', name='W9960', owner='Winbond Electronics', description='?'),
    CodecInfo(fourcc='WHAM', name='Microsoft Video 1', owner='Microsoft', description="Yet another FOURCC describing Microsoft's MSVC/CRAM codec."),
    CodecInfo(fourcc='WINX', name='Winnov Software Compression', owner='Winnov', description='Software codec used by some Winnov Videum products.'),
    CodecInfo(fourcc='WJPG', name='Winbond JPEG', owner='?', description='Format supported byAverMediaUSB TV-tuner/capture device.'),
    CodecInfo(fourcc='WMV1', name='Windows Media Video 7', owner='Microsoft', description=''),
    CodecInfo(fourcc='WMV2', name='Windows Media Video 8', owner='Microsoft', description=''),
    CodecInfo(fourcc='WMV3', name='Windows Media Video 9', owner='Microsoft', description='You may find other useful informationhere.'),
    CodecInfo(fourcc='WMVA', name='Windows Media Video 9 Advanced Profile', owner='Microsoft', description='The codec originally submitted for consideration as SMPTE VC1. This is not VC1 compliant and is no longer supported by Microsoft.'),
    CodecInfo(fourcc='WNV1', name='Winnov Hardware Compression', owner='Winnov', description='Hardware codec used by Winnov Videum products.'),
    CodecInfo(fourcc='WVC1', name='SMPTE VC1', owner='Microsoft', description="Microsoft's implementation of the SMPTE VC1 codec."),
    CodecInfo(fourcc='x263', name='Download here', owner='Xirlink', description='Another H.263 codec. This one is apparently used by an IBM-branded webcam.'),
    CodecInfo(fourcc='X264', name='H.264', owner='?', description='This FOURCC was originally registered by a company called&nbsp;XiWave but their web presence has disappeared. I am now informed that it is used by a popular open source H.264 implementation.'),
    CodecInfo(fourcc='XVID', name='XVID MPEG-4', owner='XVID', description="Codec is available in source form from XVID web site. Can also be downloaded as part of theGordian Knot Codec Pack.This FOURCC is also supported byLEAD's MCMP Codec."),
    CodecInfo(fourcc='XLV0', name='XL Video Decoder', owner='NetXL Inc.', description='?'),
    CodecInfo(fourcc='XMPG', name='XING MPEG', owner='XING Corporation', description='Editable (I frame only) MPEG codec'),
    CodecInfo(fourcc='XWV0-XWV9', name='XiWave Video Codec', owner='XiWave', description='XWV3 is currently used to describe Xi-3 Video. Others are unused.'),
    CodecInfo(fourcc='XXAN', name='?', owner='Origin?', description='Codec useing Huffman and RLE encoding paired with basic interframing. This format is used in Wing Commander 3 and 4 movies.The codec filename is xanlib.dll and a player, xanmovie, is available on the the Kilrathi Saga and Crusader game CDs.'),
    CodecInfo(fourcc='Y16', name='16bpp Grayscale Video', owner='Thermoteknix Systems Ltd.', description='A simple, uncompressed format for recording 16bpp grayscale images.'),
    CodecInfo(fourcc='Y411', name='YUV 4:1:1', owner='Microsoft', description='Supposedly 16bpp packed but 4:1:1 is usually 12bpp - odd. This is an uncompressed YUV format.'),
    CodecInfo(fourcc='Y41P', name='Brooktree YUV 4:1:1', owner='Conexant', description="This is an uncompressed YUV 411 format I registered about 7 years ago. I've stumbled on a few AVIs that use it, though, so I am listing it here. Download the ZIP and add VIDC.BT20=btvvc32.drv and VIDC.Y41P=btvvc32.drv to the [drivers32] section of your SYSTEM.INI to enable the codec"),
    CodecInfo(fourcc='Y444', name='?', owner='?', description='Format provided by the Windows 2000 drivers for the iRez&nbsp;Stealth Fire camera. Seems to be a copy of  IYU2.'),
    CodecInfo(fourcc='Y8', name='Grayscale video', owner='?', description='Probably a duplicate of the uncompressedY800format. The 2 last characters are spaces. See alsoGREYwhich appears to be another duplicate'),
    CodecInfo(fourcc='YC12', name='YUV 12 codec', owner='Intel', description='?'),
    CodecInfo(fourcc='YUV8', name='Caviar YUV8', owner='Winnov', description='?'),
    CodecInfo(fourcc='YUV9', name='YUV9 Raw Format', owner='Intel', description='An uncompressed YUV format used by Intel Indeo video products.'),
    CodecInfo(fourcc='YUVP', name='?', owner='?', description='An uncompressed YCrCb 4:2:2 format using 10-bit precision components ordered Y0 U0 Y1 V0. I have no idea how the 10 bit samples are packed - sorry.'),
    CodecInfo(fourcc='YUY2', name='Raw, uncompressed YUV 4:2:2', owner='Microsoft (probably)', description="Yes, I know this isn't a compressed format but I get so many questions about where to find a codec for YUY2 AVIs that it's here to allow people to findthe answereasily. I'm told &quot;VirtualDub has been able to decode YUY2 internally since V1.3a. Newer versions of Ben Rudiak-Gould's Huffyuv codec will also convert YUY2 or UYVY data to RGB&quot;"),
    CodecInfo(fourcc='YUYV', name='?', owner='Canopus', description="Compressed YUV format. Some of the software on theCanopus download pagemay include this codec (I'm guessing - please tell me if this is true)."),
    CodecInfo(fourcc='YV12', name='YUV 4:2:0 Planar', owner='MicrosoftorApple?', description='Uncompressed format commonly used in MPEG video processing. You can find more informatio on theYUV formats page.'),
    CodecInfo(fourcc='YV16', name='YUV 4:2:2 Planar', owner='Elecard', description='Uncompressed format similar to YV12 but with twice the chroma resolution.'),
    CodecInfo(fourcc='YV92', name='?', owner='Intel', description="Codec used by Intel's Smart Video Recorder product. Apparently a  compresssed YVU9  format."),
    CodecInfo(fourcc='ZLIB', name='?', owner='?', description='A generic lossless codec that you candownload from here. Apparently also contains theMSZHcodec. Algorithm info can be foundhere. May be the same algorithm used in compressing PNG images.'),
    CodecInfo(fourcc='ZMBV', name='The DoxBox Project', owner='DoxBox&nbsp;Capture Codec', description='A codec using ZLIB compression which is used to capture screen information.'),
    CodecInfo(fourcc='ZPEG', name='Video Zipper', owner='Metheus', description='?'),
    CodecInfo(fourcc='ZyGo', name='ZyGoVideo', owner='ZyGo Digital', description='Video codec usually packaged in Quicktime files. Investigations suggest that it may be a variant of H.263.'),
    CodecInfo(fourcc='ZYYY', name='?', owner='?', description='?')]


class CodecTest(object):
    @classmethod
    def test_codec(self, codec):
        with Silence():
            f_handle, output_path = tempfile.mkstemp(suffix='.avi') 
            output_path = path(output_path)
            writer = None
            try:
                dimensions = (640, 480)
                frame = cv.CreateImage(dimensions, cv.IPL_DEPTH_8U, 3)
                fourcc = cv.CV_FOURCC(*str(codec))
                writer = cv.CreateVideoWriter(output_path, fourcc, 24,
                                                    dimensions, True)
                result = cv.WriteFrame(writer, frame)
            except:
                result = 0
            finally:
                if writer:
                    del writer
                os.close(f_handle)
                output_path.remove()
        return not(result == 0)


def get_supported_codecs():
    return set([c for c in ALL_CODECS if CodecTest.test_codec(c.fourcc)])


def get_codec_list(url='http://www.fourcc.org/codecs.php'):
    from BeautifulSoup import BeautifulSoup

    data = urlopen(url).read()
    soup = BeautifulSoup(data)

    table = soup.find('table', {'class': 'jqdt display'})

    table_body = table.findChild('tbody')
    rows = table_body.findChildren('tr')


    return [CodecInfo(*[getattr(c, 'text') for c in row.findChildren('td')]) for row in rows]


